# Generated by Django 5.2.1 on 2025-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('optometrista', 'Optometrista'), ('recepcionista', 'Recepcionista'), ('tecnico', 'Técnico'), ('supervisor', 'Supervisor')], max_length=50)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricacion',
            fields=[
                ('id_fabricacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fabricacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_generado', models.DateField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
    ]
